version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: markdown_postgres
    environment:
      POSTGRES_USER: markdown
      POSTGRES_PASSWORD: markdown
      POSTGRES_DB: markdown
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: markdown_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "admin"]

volumes:
  postgres_data:
